### ISSUE TITLE
smbd: sys_path_to_bdev() failed for path [.]!

### ISSUE THREAD

**Issue by davidak** [davidak/nixos-config#5]
Erscheint immer wieder im Log:
```
Aug 21 21:42:29 nas smbd[14762]: [2017/08/21 21:42:29.392415,  0] ../source3/lib/sysquotas.c:461(sys_get_quota)
Aug 21 21:42:29 nas smbd[14762]:   sys_path_to_bdev() failed for path [.]!
```
Liegt vermutlich an speziellen Dateinamen.

**Comment by davidak** [comment]
Ref.:

- https://bugzilla.samba.org/show_bug.cgi?id=10541
- https://lists.samba.org/archive/samba/2010-October/158650.html

**Comment by mathiasvinicius** [comment]
I finally got a resolution in this guide.

Solution:
get quota command = /var/lib/samba/samba-btrfs-quota.sh

touch /var/log/samba/quota.log
chmod 777 /var/log/samba/quota.log

Script:
[https://bugs.launchpad.net/ubuntu/+source/samba/+bug/1735953/+attachment/5183644/+files/samba-btrfs-quota.sh](url)

Ref.:
[https://bugs.launchpad.net/ubuntu/+source/samba/+bug/1735953](url)

**Comment by davidak** [comment]
>There's a hacky workaround to disable quotas

Is there no official, clean way to disable quotas? I actually don't need them because i'm the only user.

**Comment by jones-tw** [comment]
How about re-configure samba with **--without-quotas**?
